### ISSUE TITLE
Unsupported block type

### ISSUE THREAD

**Issue by uttamanand-whs** [Tazmainiandevil/codingwithtaz#3]
Getting issue while terraforming front door for custom domain -:

---------------------------------------------------------------------------------------------------------------

Error: Unsupported argument

  on modules/module.tf line 92, in resource "azurerm_frontdoor" "instance":
  92:       custom_https_provisioning_enabled       = frontend_endpoint.value.custom_https_provisioning_enabled

An argument named "custom_https_provisioning_enabled" is not expected here.

Error: Unsupported block type

  on modules/module.tf line 95, in resource "azurerm_frontdoor" "instance":
  95:       dynamic "custom_https_configuration" {

Blocks of type "custom_https_configuration" are not expected here.

---------------------------------------------------------------------------------------------------------------
Terraform v0.14.11
+ provider registry.terraform.io/hashicorp/azurerm v2.60.0

**Comment by Tazmainiandevil** [comment]
Looks like there was a breaking change added to the azurerm provider in v2.58.0
![image](https://user-images.githubusercontent.com/4790417/139396918-bba483b5-6904-4038-be60-95e6df77c0ae.png)
